/** @type {import('next').NextConfig} */
// deployed-addresses.json is generated by `scripts/deploy.js` at the repo root.
// Fall back gracefully (instead of crashing the build) if contracts haven't
// been deployed yet, or if the frontend already has NEXT_PUBLIC_CONTRACT_ADDRESS
// set via project/.env.
let deployedContractAddress;
try {
  deployedContractAddress = require('../deployed-addresses.json').job;
} catch (err) {
  console.warn(
    '[next.config.js] Could not read ../deployed-addresses.json — run `npx hardhat run scripts/deploy.js --network sepolia` from the repo root, or set NEXT_PUBLIC_CONTRACT_ADDRESS in project/.env.'
  );
}

const nextConfig = {
  env: {
    NEXT_PUBLIC_CONTRACT_ADDRESS:
      deployedContractAddress || process.env.NEXT_PUBLIC_CONTRACT_ADDRESS,
  },
  // output: 'export',
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: { unoptimized: true },
  experimental: {
    forceSwcTransforms: false,
  },
};

module.exports = nextConfig;
